### ISSUE TITLE
Notify user if their name is already in use

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/HTML-Client#146]
Following #145 we should notify a user at login time if there is already a user connected with the same name, and give them a chance to choose a different name.

**Comment by Zomis** [comment]
Fixed.

**Comment by Phrancis** [comment]
I tested this and the issue is still occurring. Tested on production client running from master.

![image](https://user-images.githubusercontent.com/8539648/40749181-247630d8-6431-11e8-8c07-a8cb6688fb79.png)
